version: '3'
services:
  smwpf:
    build: 
      context: .
      dockerfile: dockerfile
    image: semantic-mediawiki
    ports:
      # make the wiki avaialable at http://localhost:8081
      - 8081:80
    volumes:
      - wiki-images:/var/www/html/images
      - wiki-db:/var/www/data
      # Luego del setup inicial, descargar el LocalSettings.php al mismo directorio
      # donde se encuentra este archivo yaml, y descomente la siguiente linea 
      # y use el comando compose para iniciarl el servicio
      #- ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
volumes:
  wiki-images:
  wiki-db:

      


      
